<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Positional Tracking Has Ended_leaflet-_152dae</name>
   <tag></tag>
   <elementGuidId>d30155c2-6686-4c29-aff8-ec950022bcc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>g > path:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>b6446525-8b87-4de8-bc69-25aed2310365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-interactive</value>
      <webElementGuid>ecccb7bc-5dc6-44d1-9134-3f2a3cf6545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#828483</value>
      <webElementGuid>e1f2d215-c607-4f50-a4d2-7babd3042361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-opacity</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>3dae93c0-6778-4312-9f25-ca4add7ecc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>9a789507-7bd3-4505-9845-65882af99b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>2377d13e-4889-4ef2-9dbe-b565c4c38769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>6d01195c-e293-42a1-9c90-636d39cdd4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9d9b9016-1c69-4e7d-8c9d-5e5d10f87cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M410 160L410 160M410 160L404 159M401 160L405 163L411 163L414 165L410 160L415 167L411 187L415 262L423 324L437 383L435 393L422 432L439 420L441 441</value>
      <webElementGuid>9206f479-8b59-4c6a-a5a9-d511f8d15010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;desktop__LayoutWrapper-sc-43d6t8-0 hlRtPs&quot;]/section[@class=&quot;desktop__Content-sc-43d6t8-1 QOLIU&quot;]/div[@class=&quot;layout-row__RowWrapper-sc-1uoco8s-0 kkBznr&quot;]/div[@class=&quot;layout-row__SectionContainer-sc-1uoco8s-2 YsSid&quot;]/div[2]/div[@class=&quot;layout-row__RowInner-sc-1uoco8s-1 hkmBIC&quot;]/div[@class=&quot;tracker__Wrapper-sc-1ixqjdu-0 eRXwNv&quot;]/div[@class=&quot;row__Row-sc-18xg2xa-0 iQRCGm&quot;]/div[@class=&quot;client-only-flight-map__MapWrapper-sc-yxmqy7-0 iUXUxi&quot;]/div[@class=&quot;flight-map__Wrapper-sc-172mvfy-0 kFGGyc&quot;]/div[@class=&quot;leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom&quot;]/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-overlay-pane&quot;]/svg[@class=&quot;leaflet-zoom-animated&quot;]/g[1]/path[@class=&quot;leaflet-interactive&quot;]</value>
      <webElementGuid>e522bdef-baa1-4efb-befe-66df7bc93f8d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
