<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>b290dd3d-6d3c-4e85-aa5e-5afc77944c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div[6]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.leaflet-popup-close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;×&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ed432a7-e1ba-47b0-b658-06635e655605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-popup-close-button</value>
      <webElementGuid>9c5859e2-b06e-4945-a7b8-966a12b89cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#close</value>
      <webElementGuid>26c2c2ca-b684-49b7-9737-5a6de67ab472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>6286a675-a96b-4bf2-9497-1cf5852ea750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;desktop__LayoutWrapper-sc-43d6t8-0 hlRtPs&quot;]/section[@class=&quot;desktop__Content-sc-43d6t8-1 QOLIU&quot;]/div[@class=&quot;layout-row__RowWrapper-sc-1uoco8s-0 kkBznr&quot;]/div[@class=&quot;layout-row__SectionContainer-sc-1uoco8s-2 YsSid&quot;]/div[2]/div[@class=&quot;layout-row__RowInner-sc-1uoco8s-1 hkmBIC&quot;]/div[@class=&quot;tracker__Wrapper-sc-1ixqjdu-0 eRXwNv&quot;]/div[@class=&quot;row__Row-sc-18xg2xa-0 iQRCGm&quot;]/div[@class=&quot;client-only-flight-map__MapWrapper-sc-yxmqy7-0 iUXUxi&quot;]/div[@class=&quot;flight-map__Wrapper-sc-172mvfy-0 kFGGyc&quot;]/div[@class=&quot;leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom&quot;]/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-popup-pane&quot;]/div[@class=&quot;leaflet-popup  leaflet-zoom-animated&quot;]/a[@class=&quot;leaflet-popup-close-button&quot;]</value>
      <webElementGuid>68986a45-301c-44bd-ac0e-67d3288279d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div[6]/div/a</value>
      <webElementGuid>0c72c487-743f-4833-8e9e-0bb25e22e108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'×')]</value>
      <webElementGuid>b93726ec-09d2-48ef-b1b9-88895dcd3239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positional Tracking Has Ended'])[1]/following::a[2]</value>
      <webElementGuid>a97ccafc-ce19-472f-bc63-c90c59abe37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::a[1]</value>
      <webElementGuid>39057cac-fc32-405b-b976-15c9cb3c6f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>7facb600-c427-4e49-9c3c-197d2aac2e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#close')]</value>
      <webElementGuid>3a8ff0b0-491d-4f33-bcb9-8971de86aa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>65a8cc08-3a09-45ba-b931-768c129174d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#close' and (text() = '×' or . = '×')]</value>
      <webElementGuid>6ceb6fab-84d6-40dd-921e-3a43f33abc19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
