<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Airline_airlineInput</name>
   <tag></tag>
   <elementGuidId>cad43da8-5d69-473b-9ca7-783b5aef1bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='airlineInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;airlineInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ft-flight-search >> internal:attr=[placeholder=&quot;Example: AA or American Airlines&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d586b6e-a5ca-43c8-891f-bc4df6ae1317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>async-common__StyledInput-sc-6djn13-0 bYKSYy</value>
      <webElementGuid>7290e71a-f6ef-42e4-a373-26b57a7dbf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: AA or American Airlines</value>
      <webElementGuid>e7502c82-c5ea-4dfe-bb49-0b78a08214c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>airlineInput</value>
      <webElementGuid>81484c66-6e37-46f2-b3c6-d9e7aa77eccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ft-flight-search&quot;)/div[@class=&quot;utility-components__FormFieldRow-sc-b8nvu2-1 kkStkg&quot;]/div[@class=&quot;async-common__SelectContainer-sc-6djn13-2 jIPLoc&quot;]/div[@class=&quot;async-common__InputContainer-sc-6djn13-1 cfclQi&quot;]/input[@class=&quot;async-common__StyledInput-sc-6djn13-0 bYKSYy&quot;]</value>
      <webElementGuid>bc10158b-13ef-4cf1-bc24-7c29cd0f70d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='airlineInput']</value>
      <webElementGuid>cdd77090-09bd-4de5-a794-8835fdda5f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ft-flight-search']/div/div/div/input</value>
      <webElementGuid>fc732b10-1f04-49c9-b5f8-e536f3d5500a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>28591259-7e91-48e8-a571-829ce742c47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Example: AA or American Airlines' and @name = 'airlineInput']</value>
      <webElementGuid>45285ada-e714-4fd7-a6c9-c9a414da40e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
